test: build
	bats tests

.PHONY: test build


# The bootstrap script adds basher's physical directory to PATH:
# It is built from bashup/realpaths + libexec/basher.stub

BOOTSTRAP=libexec/basher.realpath

build: $(BOOTSTRAP)

$(BOOTSTRAP): vendor/bashup/realpaths/realpaths libexec/basher.stub
	echo "#!/usr/bin/env bash" >$@
	echo "# This file is automatically generated by makefile; do not edit!" >>$@
	echo >>$@
	cat $^ >>$@
