#!/usr/bin/env bash
# Summary: Uninstalls a package
# Usage: basher uninstall <package>

package="$1"

if [ -z "$package" ]; then
  basher-help uninstall
  exit 1
fi

source "$BASHER_PACKAGES_PATH/$package/package.sh"

IFS=: read -a bins <<< "$BIN"

for bin in "${bins[@]}"; do
  rm "$BASHER_ROOT/cellar/bin/${bin##*/}"
done

rm -rf "${BASHER_PACKAGES_PATH}/$package"
