#!/usr/bin/env bash
#
# Usage: basher _deps <package>
# Summary: Globally installs package runtime dependencies
#
# Installs the package runtime dependencies, specified with
# the DEPS= variable on package.sh.
#
# Does not install test dependencies.
#
# Example: DEPS=username/repo1:otheruser/repo2

set -e

if [ "$#" -ne 1 ]; then
  basher-help _deps
  exit 1
fi

package="$1"

shopt -s nullglob

basher-_validate "$package"

source "$BASHER_PACKAGES_PATH/$package/package.sh" # TODO: make this secure?
IFS=: read -a deps <<< "$DEPS"

for dep in "${deps[@]}"
do
  basher-install "$dep"
done
