#!/usr/bin/env bash
# Summary: Creates a new package
# Usage: basher new <package-name>

set -e

if [ "$#" -ne 1 ]; then
  basher-help new
  exit 1
fi

package="$1"

if [ -e "$package" ]; then
  echo "Directory '$package' already exists."
  exit 1
fi

mkdir "$package"
touch "$package/package.sh"
