#!/usr/bin/env bash

package="$1"

shopt -s nullglob

bins=($BASHER_PACKAGES_PATH/$package/bin/*)
bins=("${bins[@]##*/}")
bins=("${bins[@]/#/bin/}")

for bin in "${bins[@]}"
do
  ln -sf "$BASHER_PACKAGES_PATH/$package/$bin" "$BASHER_ROOT/cellar/bin/${bin##*/}"
  chmod +x "$BASHER_ROOT/cellar/bin/${bin##*/}"
done
