#!/usr/bin/env bash
#
# Summary: Clones a package from github, but doesn't install it
# Usage: basher clone <package>

set -e

if [ "$#" -ne 1 ]; then
  basher-help clone
  exit 1
fi

package="$1"

if [ -z "$package" ]; then
  basher-help clone
  exit 1
fi

IFS=/ read -r user name <<< "$package"

if [ -z "$user" ]; then
  basher-help clone
  exit 1
fi

if [ -z "$name" ]; then
  basher-help clone
  exit 1
fi

if [ -e "$BASHER_PACKAGES_PATH/$package" ]; then
  echo "Package '$package' is already present"
  exit 1
fi

git clone "git://github.com/$package.git" "${BASHER_PACKAGES_PATH}/$package"
