#!/usr/bin/env bash
#
# Summary: Display help for a command
#
# Usage: basher help [--usage] <command>

set -e

command="$1"

if [ -z "$command" ]; then
  exec lasher _help basher
fi

lasher _help basher "$command"
