#!/usr/bin/env bash
# Summary: Installs a package from github
# Usage: basher install <package>

set -e

if [ "$#" -ne 1 ]; then
  basher-help install
  exit 1
fi

package="$1"

if [ -z "$package" ]; then
  basher-help install
  exit 1
fi

IFS=/ read -r user name <<< "$package"

if [ -z "$user" ]; then
  basher-help install
  exit 1
fi

if [ -z "$name" ]; then
  basher-help install
  exit 1
fi

basher-_clone "$package"
basher-_deps "$package"
basher-_link-bins "$package"
basher-_link-man "$package"
