#!/usr/bin/env bash
#
# Summary: Outputs the runtime path for a package
# Usage: source "$(basher runtime-path <package>)"

set -e

# TAG completions
if [ "$1" == "--complete" ]; then
  exec basher-list
fi

if [ "$#" -ne 1 ]; then
  basher-help runtime-path
  exit 1
fi

package="$1"

basher-_validate "$package"

if [ -e "$BASHER_PACKAGES_PATH/$package/package.sh" ]; then
  source "$BASHER_PACKAGES_PATH/$package/package.sh" # TODO: make this secure?
  IFS=: read -a runtime <<< "$RUNTIME"
fi

if [ -z "$RUNTIME" ]; then
  echo "ERROR: package '$package' does not export a runtime."
  exit 1
fi

echo "$BASHER_PACKAGES_PATH/$package/$RUNTIME"
