#!/usr/bin/env bash
#
# Summary: Clones a package from github, but doesn't install it
# Usage: basher _clone <package>

set -e

if [ "$#" -ne 1 ]; then
  basher-help _clone
  exit 1
fi

package="$1"

if [ -z "$package" ]; then
  basher-help _clone
  exit 1
fi

IFS=/ read -r user name <<< "$package"

if [ -z "$user" ]; then
  basher-help _clone
  exit 1
fi

if [ -z "$name" ]; then
  basher-help _clone
  exit 1
fi

if [ -e "$BASHER_PACKAGES_PATH/$package" ]; then
  echo "Package '$package' is already present"
  exit 0
fi

if [ "$BASHER_FULL_CLONE" = "true" ]; then
  DEPTH_OPTION=""
else
  DEPTH_OPTION="--depth=1"
fi

git clone ${DEPTH_OPTION} --recursive "https://github.com/$package.git" "${BASHER_PACKAGES_PATH}/$package"
