#!/usr/bin/env bash
#
# Summary: A package manager for shell scripts
#
# Usage: basher <command> [<args>]

if [ -z "$BASHER_ROOT" ]; then
  BASHER_ROOT="$HOME/.basher"
fi
export BASHER_ROOT

if [ -z "$BASHER_PREFIX" ]; then
  BASHER_PREFIX="$BASHER_ROOT/cellar"
fi
export BASHER_PREFIX

if [ -z "$BASHER_PACKAGES_PATH" ]; then
  BASHER_PACKAGES_PATH="$BASHER_PREFIX/packages"
fi
export BASHER_PACKAGES_PATH

if [ -z "$BASHER_INSTALL_BIN" ]; then
  BASHER_INSTALL_BIN="$BASHER_PREFIX/bin"
fi
export BASHER_INSTALL_BIN

if [ -z "$BASHER_INSTALL_MAN" ]; then
  BASHER_INSTALL_MAN="$BASHER_PREFIX/man"
fi
export BASHER_INSTALL_MAN

command="$1"
case "$command" in
"")
  basher-help
  ;;
* )
  command_path="$(command -v "basher-$command" || true)"
  if [ -z "$command_path" ]; then
    echo "basher: no such command '$command'" >&2
    exit 1
  fi

  shift 1
  exec "$command_path" "$@"
  ;;
esac
