#!/usr/bin/env bash
# Summary: Configure the shell environment for basher
# Usage: eval "$(basher init -)"

set -e

shell="$2"
if [ -z "$shell" ]; then
  shell="$(ps c -p "$PPID" -o 'ucomm=' 2>/dev/null || true)"
  shell="${shell##-}"
  shell="${shell%% *}"
  shell="$(basename "${shell:-$SHELL}")"
fi

print_fish_commands() {
  echo "setenv BASHER_SHELL $shell"
  echo "setenv BASHER_ROOT $BASHER_ROOT"

  echo 'if not contains $BASHER_ROOT/cellar/bin $PATH'
  echo 'setenv PATH $BASHER_ROOT/cellar/bin $PATH'
  echo 'end'
}

print_sh_commands(){
  echo "export BASHER_SHELL=$shell"
  echo "export BASHER_ROOT=$BASHER_ROOT"

  echo 'export PATH="$BASHER_ROOT/cellar/bin:$PATH"'

  # TODO: is only read by sh type shells (not Fish)
  echo 'source "$BASHER_ROOT/runtime/require.bash"'
}

case "$shell" in
  fish )
    print_fish_commands
    ;;
  * )
    print_sh_commands
    ;;
esac

if [ -e "$BASHER_ROOT/completions/basher.$shell" ]; then
  echo "source \"\$BASHER_ROOT/completions/basher.$shell\""
fi
