#!/usr/bin/env bash
#
# Summary: Clones a package from a site, but doesn't install it
#
# Usage: basher _clone <site> <package>

set -e

if [ "$#" -ne 2 ]; then
  basher-help _clone
  exit 1
fi

site="$1"
package="$2"

if [ -z "$site" ]; then
  basher-help _clone
  exit 1
fi

if [ -z "$package" ]; then
  basher-help _clone
  exit 1
fi

IFS=/ read -r user name <<< "$package"

if [ -z "$user" ]; then
  basher-help _clone
  exit 1
fi

if [ -z "$name" ]; then
  basher-help _clone
  exit 1
fi

if [ -e "$BASHER_PACKAGES_PATH/$package" ]; then
  echo "Package '$package' is already present"
  exit 0
fi

if [ "$BASHER_FULL_CLONE" = "true" ]; then
  DEPTH_OPTION=""
else
  DEPTH_OPTION="--depth=1"
fi

git clone ${DEPTH_OPTION} --recursive "https://${site}/$package.git" "${BASHER_PACKAGES_PATH}/$package"
