#!/usr/bin/env bash
# Summary: Configure the shell environment for basher
# Usage: eval "$(basher init -)"

set -e

shell="$2"
if [ -z "$shell" ]; then
  shell="$(ps c -p "$PPID" -o 'ucomm=' 2>/dev/null || true)"
  shell="${shell##-}"
  shell="${shell%% *}"
  shell="$(basename "${shell:-$SHELL}")"
fi

echo "export BASHER_SHELL=$shell"
echo "export BASHER_ROOT=$BASHER_ROOT"

echo 'export PATH="$BASHER_ROOT/cellar/bin:$PATH"'

if [ -e "$BASHER_ROOT/completions/basher.$shell" ]; then
  echo "source \"\$BASHER_ROOT/completions/basher.$shell\""
fi


echo 'source "$BASHER_ROOT/runtime/require.bash"'
