#!/usr/bin/env bash

package="$1"

bins=($BASHER_PACKAGES_PATH/$package/bin/*)
bins=("${bins[@]##*/}")
bins=("${bins[@]/#/bin/}")

for bin in "${bins[@]}"; do
  rm -f "$BASHER_ROOT/cellar/bin/${bin##*/}"
done

if [ -e "$BASHER_PACKAGES_PATH/$package/bin" ]; then
  exit 0
fi

bins=($(find "$BASHER_PACKAGES_PATH/$package" -maxdepth 1 -perm +111 -type f -or -type l))
bins=("${bins[@]##*/}")

for bin in "${bins[@]}"
do
  rm -f "$BASHER_ROOT/cellar/bin/$bin"
done
