#!/usr/bin/env bash
#
# Usage: basher _validate <package>
# Summary: Validates a basher package
#
# A package is valid if it contains a package.sh file,
# even if it is empty.

set -e

if [ "$#" -ne 1 ]; then
  basher-help _validate
  exit 1
fi

package="$1"

if [ ! -e "$BASHER_PACKAGES_PATH/$package/package.sh" ]; then
  echo "ERROR: package.sh not found."
  exit 1
fi
