#!/usr/bin/env bash
# Summary: Configure the shell environment for basher
# Usage: eval "$(basher init -)"

echo "export BASHER_ROOT=$BASHER_ROOT"
echo "source $BASHER_ROOT/runtime/path.bash"
echo "source $BASHER_ROOT/runtime/require.bash"
