#!/usr/bin/env bash
# Summary: Installs a package from github
# Usage: basher install <user> <package>

set -e

username="$1"
package="$2"

if [ -z "$username" ]; then
  basher-help install
  exit 1
fi

if [ -z "$package" ]; then
  basher-help install
  exit 1
fi

basher-clone "$username" "$package"

shopt -s nullglob

if [ -e "$BASHER_PACKAGES_PATH/$package/package.sh" ]; then
  source "$BASHER_PACKAGES_PATH/$package/package.sh" # TODO: make this secure?
  IFS=: read -a bins <<< "$BIN"
else
  echo "WARNING: package.sh not found, linking any binaries in bin directory"
  bins=($BASHER_PACKAGES_PATH/$package/bin/*)
  bins=("${bins[@]##*/}")
  bins=("${bins[@]/#/bin/}")
fi

for bin in "${bins[@]}"
do
  ln -s "$BASHER_PACKAGES_PATH/$package/$bin" "$BASHER_ROOT/cellar/bin/${bin##*/}"
done
