#!/usr/bin/env bash
#
# Summary: List all available basher commands
# Usage: basher commands

IFS=: paths=($PATH)

shopt -s nullglob

{ for path in "${paths[@]}"; do
    for command in "${path}/basher-"*; do
      command="${command##*basher-}"
      echo ${command}
    done
  done
} | sort | uniq
