#!/usr/bin/env bash

package="$1"

shopt -s nullglob

if [ -e "$BASHER_PACKAGES_PATH/$package/package.sh" ]; then
  source "$BASHER_PACKAGES_PATH/$package/package.sh" # TODO: make this secure?
  IFS=: read -a bins <<< "$BIN"
else
  echo "ERROR: package.sh not found."
  exit 1
fi

for bin in "${bins[@]}"
do
  ln -sf "$BASHER_PACKAGES_PATH/$package/$bin" "$BASHER_ROOT/cellar/bin/${bin##*/}"
  chmod +x "$BASHER_ROOT/cellar/bin/${bin##*/}"
done
