#!/usr/bin/env bash
# Summary: Uninstalls a package
# Usage: basher uninstall <package>

set -e

package="$1"

if [ -z "$package" ]; then
  basher-help uninstall
  exit 1
fi

shopt -s nullglob

if [ ! -d "$BASHER_PACKAGES_PATH/$package" ]; then
  echo "Package '$package' is not installed"
  exit 1
fi

if [ -e "$BASHER_PACKAGES_PATH/$package/package.sh" ]; then
  source "$BASHER_PACKAGES_PATH/$package/package.sh"
  IFS=: read -a bins <<< "$BIN"
else
  echo "WARNING: package.sh not found, unlinking any binaries in bin directory"
  bins=($BASHER_PACKAGES_PATH/$package/bin/*)
  bins=("${bins[@]##*/}")
fi

for bin in "${bins[@]}"; do
  rm "$BASHER_ROOT/cellar/bin/${bin##*/}"
done

rm -rf "${BASHER_PACKAGES_PATH}/$package"
