#!/usr/bin/env bash
# Summary: Upgrades a package
# Usage: basher upgrade <package|[-a/--all]> 

set -e

case $1 in
  -a|--all)
    upgrade_all="true"
    shift
  ;;
esac

if [ -n "$upgrade_all" ]; then
  for package_path in ${BASHER_PACKAGES_PATH}/*/*
  do
    username="$(dirname "$package_path")"
    username="${username##*/}"
    package="${package_path##*/}"

    echo "Upgrading $username/$package..."
    cd "$package_path"
    git pull
  done
  exit
fi

if [ "$#" -ne 1 ]; then
  basher-help upgrade
  exit 1
fi

# TAG completions
if [ "$1" == "--complete" ]; then
  exec basher-list
fi

package="$1"

if [ -z "$package" ]; then
  basher-help upgrade
  exit 1
fi

IFS=/ read -r user name <<< "$package"

if [ -z "$user" ]; then
  basher-help upgrade
  exit 1
fi

if [ -z "$name" ]; then
  basher-help upgrade
  exit 1
fi

cd "${BASHER_PACKAGES_PATH}/$package"
git pull
