#!/usr/bin/env bash

package="$1"

bins=($BASHER_PACKAGES_PATH/$package/bin/*)
bins=("${bins[@]##*/}")
bins=("${bins[@]/#/bin/}")

for bin in "${bins[@]}"; do
  rm -f "$BASHER_ROOT/cellar/bin/${bin##*/}"
done
